server {
    listen 80;
    server_name mit-project.me www.mit-project.me;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name mit-project.me www.mit-project.me;

    ssl_certificate /etc/letsencrypt/live/mit-project.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mit-project.me/privkey.pem;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
