services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: mit_project
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:pwd@db:5432/mit_project
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
